---
- hosts: all
  become: true
  gather_facts: true

  roles:
    - role: hifis.toolkit.unattended_upgrades
      unattended_automatic_reboot_time: "03:30"
      when: ansible_facts['os_family'] == 'Debian'

  tasks:
    - name: update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day
      when: ansible_facts['os_family'] == 'Debian'

#    - name: update and upgrade dnf packages
#      ansible.builtin.dnf:
#        name: "*"
#        state: latest
#      when: ansible_facts['os_family'] == 'RedHat'

    - name: check if reboot needed
      stat:
        path: /var/run/reboot-required
      register: check_reboot
      changed_when: false

    - name: reboot system (if necessary)
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        post_reboot_delay: 120
      when: check_reboot.stat.exists

- hosts: network
  become: true
  roles:
    - role: maas_controller
      when: use_maas

- hosts: storage_servers
  become: true
  roles:
    - role: zfs_host
      when: use_zfs_host
    - role: stash_host
      when: use_stash
    - role: cockpit-nas
      when: use_cockpit
    - role: fiberchannel_target_host
      when: use_fiberchannel_target_host
    - role: docker_host
      vars:
        docker_data_root: /tank/docker/
      when: use_docker_host

- hosts: proxmox_servers
  become: true
  pre_tasks:
  - name: Ensure enterprise Ceph apt repository is absent
    ansible.builtin.apt_repository:
      repo: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
      state: absent
      filename: ceph
    when: use_pve

  - name: Ensure non-enterprise Ceph apt repository is present
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
      state: present
      filename: ceph
    when: use_pve

  - name: Ensure enterprise Proxmox (PVE) apt repositories is absent
    ansible.builtin.apt_repository:
      repo: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
      state: absent
      filename: pve-enterprise
    when: use_pve

  - name: Ensure non-enterprise Proxmox (PVE) apt repositories are present
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
      state: present
    when: use_pve

  - name: Ensure enterprise Proxmox (PBS) apt repositories is absent
    ansible.builtin.apt_repository:
      repo: deb https://enterprise.proxmox.com/debian/pbs bookworm pbs-enterprise
      state: absent
      filename: pve-enterprise
    when: use_pbs

  - name: Ensure non-enterprise Proxmox (PBS) apt repositories are present
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription
      state: present
    when: use_pbs

  roles:
  - role: ansible-keepalived
    vars:
      keepalived_instances:
        internal:
          interface: "{{ vrrp_nic | default(ansible_default_ipv4.interface, true) }}"
          state: "{{ (groups['pve_servers'].index(inventory_hostname) == 0) | ternary('MASTER','BACKUP') }}"
          virtual_router_id: "{{ virtual_router_id }}"
          priority: "{{ (inventory_hostname == groups['pve_servers'][0]) | ternary('250', '100') }}"
          vips:
          - "{{ virtual_ip }} dev {{ vrrp_nic | default(ansible_default_ipv4.interface, true) }}"
    when: use_keepalived

- hosts: gitlab_servers
  become: true
  
  roles:
    - role: hifis.toolkit.gitlab